name: "Freeza91's blogs"
description: Blogging about life and tech
meta_description: record evething

markdown: kramdown
highlighter: pygments
logo: false
paginate: 2000
baseurl: /
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'freeza91'
